site_name: Emmetthor's Competitive Programming Skills

theme:
  name: material
  palette:
    - scheme: slate
      primary: custom
      accent: custom

  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate

nav:
  - 首頁: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - web_codes/javascripts/mermaid_init.js
  
extra_css:
  - web_codes/stylesheets/extra.css
