name: Board Consistency Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Configure Debug Build
        run: |
          cmake -B ${{ github.workspace }}/build-debug -S . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="-DENGINE_DEBUG"

      - name: Build Debug
        run: |
          cmake --build ${{ github.workspace }}/build-debug --config Debug

      - name: Opening Board Consistency
        run: |
          python tests/board_consistency.py \
            --engine build-debug/Hynobius \
            --file tests/board_consistency/openings_bc.txt \
            --depth 7

      - name: Middle Game Board Consistency
        run: |
          python tests/board_consistency.py \
            --engine build-debug/Hynobius \
            --file tests/board_consistency/middle_game_bc.txt \
            --depth 5

      - name: End Game Board Consistency
        run: |
          python tests/board_consistency.py \
            --engine build-debug/Hynobius \
            --file tests/board_consistency/end_game_bc.txt \
            --depth 8

      - name: Stress Board Consistency
        run: |
          python tests/board_consistency.py \
            --engine build-debug/Hynobius \
            --file tests/board_consistency/stress_bc.txt \
            --depth 2