name: Regression

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Configure Debug Build
        run: |
          cmake -B ${{ github.workspace }}/build-debug -S . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="-DENGINE_DEBUG"

      - name: Build Debug
        run: |
          cmake --build ${{ github.workspace }}/build-debug --config Debug

      - name: Mate In One
        run: |
          python tests\checkmate.py \
            --engine build-debug/Hynobius \
            --file tests\checkmate\Mate_In_One.txt \
            --mate-depth 1

      - name: Mate In Two
        run: |
          python tests\checkmate.py \
            --engine build-debug/Hynobius \
            --file tests\checkmate\Mate_In_Two.txt \
            --mate-depth 2