name: Format Check

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run format check
        run: |
          clang-format --dry-run --Werror $(git ls-files '*.cpp' '*.h')