name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -S . \
          -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer"
      - name: Build
        run:
          cmake --build ${{github.workspace}}/build
      - name: Board Consistency Test
        working-directory: ${{github.workspace}}/build
        run: ctest -R BoardConsistencyTest --verbose
