name: Regression

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Configure Release Build
        run: |
          cmake -B ${{ github.workspace }}/build-release -S . \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: |
          cmake --build ${{ github.workspace }}/build-release --config Release

      - name: Perft regression
        run: |
          python tests/regression_test.py