name: Run Tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Configure Release Build
        run: |
          cmake -B ${{ github.workspace }}/build-release -S . \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: |
          cmake --build ${{ github.workspace }}/build-release --config Release

      - name: Configure Debug Build
        run: |
          cmake -B ${{ github.workspace }}/build-debug -S . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="-DENGINE_DEBUG"

      - name: Build Debug
        run: |
          cmake --build ${{ github.workspace }}/build-debug --config Debug

  board-consistency:
    needs: build
    uses: ./.github/workflows/board-consistency.yml

  perft:
    needs: board-consistency
    uses: ./.github/workflows/perft.yml
  
  check-mate:
    needs: board-consistency
    uses: ./.github/workflows/checkmate.yml

  regression:
    needs: board-consistency
    uses: ./.github/workflows/regression.yml